FROM node:10

LABEL "com.github.actions.name"="Deploy Luxfactor Site"
LABEL "com.github.actions.description"="Do all the things!"
LABEL "com.github.actions.icon"="arrow-up-circle"
LABEL "com.github.actions.color"="purple"

ADD entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
